name: selfspy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - lockfile
  - pycrypto
  - cryptography
  - keyring
  - sqlalchemy
  - tk
  - python-xlib
  - pygobject
  - pip
  - pip:
    - dbus-python
    - secretstorage
