name: selfspy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pygobject
  # Note that secretstorage version 3.1.0 has a bug when used with keyring.
  - pip
  - pip:
    - -r file:requirements.txt
