name: selfspy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - sqlalchemy>=1.3
  - pycrypto>=2.6.1
  - cryptography=3.0
  # secretstorage version 3.1.0 has a bug when used with keyring.
  - secretstorage>=3.1.1
  - keyring>=21.3
  - lockfile
  - tk
  - python-xlib
  - pygobject
  - pip
  - pip:
    - dbus-python
