name: selfspy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - lockfile
  - pycrypto
  - cryptography
  # secretstorage version 3.1.0 has a bug when used with keyring.
  - secretstorage>=3.1.1
  - keyring
  - sqlalchemy
  - tk
  - python-xlib
  - pygobject
  - pip
  - pip:
    - dbus-python
